# Generated by Django 5.1.1 on 2024-09-10 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "Name",
                    models.CharField(
                        max_length=50, verbose_name="Наименование продукта"
                    ),
                ),
                (
                    "Description",
                    models.TextField(max_length=1000, verbose_name="Описание продукта"),
                ),
            ],
            options={
                "verbose_name": "Продукт",
                "verbose_name_plural": "Продукты",
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "Name",
                    models.CharField(
                        help_text="Введите название продукта",
                        max_length=50,
                        verbose_name="Наименование",
                    ),
                ),
                (
                    "Description",
                    models.TextField(
                        help_text="Введите описание продукта",
                        max_length=1000,
                        verbose_name="Описание",
                    ),
                ),
                (
                    "Image",
                    models.ImageField(
                        help_text="Загрузите изображение продукта",
                        upload_to="products/",
                        verbose_name="Изображение продукта",
                    ),
                ),
                (
                    "Purchase_price",
                    models.ImageField(
                        help_text="Введите цену",
                        upload_to="",
                        verbose_name="Цена за покупку",
                    ),
                ),
                (
                    "created_at",
                    models.DateField(auto_now_add=True, verbose_name="Дата создания"),
                ),
                (
                    "updated_at",
                    models.DateField(
                        auto_now=True, verbose_name="Дата последнего изменения"
                    ),
                ),
                (
                    "Category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="Product",
                        to="catalog.category",
                        verbose_name="Продукт",
                    ),
                ),
            ],
            options={
                "verbose_name": "Продукт",
                "verbose_name_plural": "Продукты",
                "ordering": ["Name", "Category"],
            },
        ),
    ]
