# Generated by Django 5.1.1 on 2024-09-12 03:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_alter_product_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={
                "verbose_name": "Категорию продукта",
                "verbose_name_plural": "Категория",
            },
        ),
        migrations.AlterField(
            model_name="category",
            name="description",
            field=models.TextField(
                help_text="Введите описание категории",
                max_length=1000,
                verbose_name="Описание каиегории",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(
                help_text="Введите название категории",
                max_length=50,
                verbose_name="Наименование каиегории",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                blank=True,
                help_text="Выберете категорию продукта",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="Product",
                to="catalog.category",
                verbose_name="Категория",
            ),
        ),
    ]
