# Generated by Django 5.1.1 on 2024-09-12 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_alter_category_options_alter_category_description_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={
                "verbose_name": "Категорию продукта",
                "verbose_name_plural": "Категории",
            },
        ),
        migrations.AlterField(
            model_name="category",
            name="description",
            field=models.TextField(
                help_text="Введите описание категории",
                max_length=1000,
                verbose_name="Описание категории",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(
                help_text="Введите название категории",
                max_length=50,
                verbose_name="Наименование категории",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="Product",
                to="catalog.category",
                verbose_name="Продукт",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="purchase_price",
            field=models.ImageField(
                blank=True,
                help_text="Введите цену",
                null=True,
                upload_to="",
                verbose_name="Цена за покупку",
            ),
        ),
    ]
