# Generated by Django 5.1.1 on 2024-10-04 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0009_blog"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Blog",
        ),
    ]
