# Generated by Django 5.1.1 on 2024-10-27 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0012_product_owner"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ["name", "category"],
                "permissions": [
                    ("can_unpublish_product", "Can unpublish product"),
                    ("can_edit_any_product", "Can edit any product"),
                ],
                "verbose_name": "Продукт",
                "verbose_name_plural": "Продукты",
            },
        ),
    ]
